spring:
  application:
    name:
      wufangquan
  datasource:
#    url: jdbc:mariadb://localhost:43306/wufangquan
#    account: root
#    password: 123456
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:43307/wufangquan?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: W2316195243
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    redis:
      host: localhost
      port: 46379
#      password: your-password
      timeout: 2000
  security:
    user:
      name: admin
      password: p[];'\,./
      roles: ADMIN
  elasticsearch:
    uris: http://localhost:49200

server:
  port: 48080

springdoc:
  api-docs:
    path: /api-docs  # 配置 OpenAPI 文档的路径
    enabled: true
  swagger-ui:
    path: /swagger-ui.html  # 配置 Swagger UI 的路径
    enabled: true  # 启用 Swagger UI

jwt:
  secret:
    EKLUF4cU6FuytxSFpddH86/+YptlWf9vHBuWcg==MsPJfkUBpd25DCKvmCusPLAl
# 日志配置
logging:
  level:
    root: INFO  # 根日志级别
    org.springframework.web: DEBUG  # Web 相关的日志级别
    com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor: debug  # MyBatis-Plus
    com.example.mapper: debug  # 你自己的 Mapper 包路径

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 控制台输出格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

netty:
  port:
    48888

kkFile:
  address:
    http://localhost:48012
